server.port: 8080

endpoints.health.enabled: true

spring.cloud.config.enabled: false

eureka.client:
    registerWithEureka: false
    fetchRegistry: false

ribbon:
  serverListRefreshInterval: 1000
  ConnectTimeout: 6000
  ReadTimeout: 3000

hystrix.commanddefault.execution.isolation.thread.timeoutInMilliseconds: 10000

feign.hystrix.enabled: true

hazelcast.max.no.heartbeat.seconds: 60

biz-application.url: http://localhost:9601
