server.port: 7001
spring.application.name: discovery-server

eureka:
  instance:
    hostname: localhost
    leaseRenewalIntervalInSeconds: 2
    leaseExpirationDurationInSeconds: 2
  server:
    evictionIntervalTimerInMs: 1000
    response-cache-update-interval-ms: 1000
  client:
    registerWithEureka: false
    fetchRegistry: false
