server.port: 8001
spring.application.name: discovery-server

eureka:
  server:
    evictionIntervalTimerInMs: 2000
    response-cache-update-interval-ms: 2000
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url.defaultZone: http://localhost:${server.port}/eureka
